service: ecs-instance-drainer

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - autoscaling:CompleteLifecycleAction
        - ecs:ListContainerInstances
        - ecs:DescribeContainerInstances
        - ecs:UpdateContainerInstancesState
        - sns:Publish
        - ec2:DescribeInstances
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - handler.py

functions:
  ecs-instance-drainer:
    handler: handler.lambda_handler
